:_content-type: PROCEDURE

:QS-path: {helloworld-QS-path}

[id="creating-a-maven-project-for-a-simple-web-application_{context}"]
= Creating a Maven project for a web application

Create a Maven project by using the `maven-archetype-webapp` archetype to get started with building web-applications for {ProductShortname} deployment. Maven provides different archetypes to create projects based on templates specific to different project types. The `maven-archetype-webapp` creates a project with the structure required to develop simple web-applications.

.Prerequisites

* You have installed Maven. For more information, see link:https://maven.apache.org/download.cgi[Downloading Apache Maven].

.Procedure

. Set up a Maven project using the `mvn` command. The command creates the directory structure for the project and the `pom.xml` configuration file.
+
[source,options="nowrap",subs=attributes]
----
$ mvn archetype:generate \
-DgroupId={helloworld-QS-groupId} \
-DartifactId={helloworld-QS-artifactId} \
-DarchetypeGroupId=org.apache.maven.archetypes \
-DarchetypeArtifactId=maven-archetype-webapp \
-DinteractiveMode=false
----

. Navigate to the application root directory:
+
[source,options="nowrap",subs=attributes]
----
$ cd {helloworld-QS-artifactId}
----

. Update the content of the generated `pom.xml`.

.. Remove the content between the `<project ...>` element  and its corresponding closing `</project>` tag.
+
Add the following elements between the `<project>` and `</project>` tags.

.. Define the following properties for the project. You can use the values defined in the __<property>__ element throughout the project by using the ${__<property>__} syntax.
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[{propertiesLines}]
----
+
** `<version.server.bom>`: Define the {ProductShortname} BOM version to use.
** `<version.server>`: Define the {ProductShortname} release version for which the application is being created.
**  `<version.wildfly.maven.plugin>`: Define the version for {ProcuctShortname} Maven plugin.

.. Define the repositories in which Maven looks for artifacts to download in these repositories.
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[{repositoriesLine}]
----
+

.. Define the repositories in which Maven looks for plug-ins to download in these repositories.
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[{pluginRepositoriesLine}]
----

.. Specify the {ProductShortname} Jakarta EE spec BOM to control the versions of runtime Maven dependencies. When you specify a BOM in the `<dependency-management>` section, you do not need to specify the versions of the provided Maven dependencies.
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[{dependencyManagentLine}]
----

////
.. Update the dependencies to look like this:
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[lines=121..143;178]
----
////

.Verification

* In the application root directory, enter the following command to download the Maven dependencies:
+
[source,options="nowrap"]
----
$ mvn install
----
+
You get an output similar to the following:
+
[source,options="nowrap"]
----
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
...
----

You can now create a web-application.
