:_content-type: PROCEDURE

:QS-path: {helloworld-QS-path}

[id="creating-a-maven-project-for-a-simple-web-application_{context}"]
= Creating a Maven project for a web application

For creating a web-application, create a Maven project with the required dependencies and the directory structure.

.Prerequisites

* You have installed Maven. For more information, see link:https://maven.apache.org/download.cgi[Downloading Apache Maven].

.Procedure

. Set up a Maven project using the `mvn` command. The command creates the directory structure for the project and the `pom.xml` configuration file.
+
[source,options="nowrap",subs=attributes]
----
$ mvn archetype:generate \
-DgroupId={helloworld-QS-groupId} \
-DartifactId={helloworld-QS-artifactId} \
-DarchetypeGroupId=org.apache.maven.archetypes \
-DarchetypeArtifactId=maven-archetype-webapp \
-DinteractiveMode=false
----

. Navigate to the application root directory:
+
[source,options="nowrap",subs=attributes]
----
$ cd {helloworld-QS-artifactId}
----

. Update the content of the generated `pom.xml`.

.. Set the following properties:
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[lines=45..49;51]
----

.. Add the following repositories:
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[lines=53..82]
----

.. Add the following plugin repositories:
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[lines=83..106]
----

.. Add the following dependency management:
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[lines=108..119]
----

////
.. Update the dependencies to look like this:
+
[source,xml,options="nowrap"]
----
include::quickstart/helloworld/pom.xml[lines=121..143;178]
----
////

.Verification

* In the application root directory, enter the following command:
+
[source,options="nowrap"]
----
$ mvn install
----
+
You get an output similar to the following:
+
[source,options="nowrap"]
----
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
...
----

You can now create a web-application.
